<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f16dd08c-9fc6-4709-a180-60db54484cd2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 42 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
